baseURL = 'https://marosluuce.github.io'
languageCode = 'en-us'
title = "marosluuce"
theme = 'hugo-coder'

[markup.goldmark.renderer]
unsafe = true

[[languages.en.menu.main]]
name = "Posts"
url = "posts/"

[caches.images]
dir = ':cacheDir/images'
